// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPAUcWJQrn2XPQOCwME-sqSb5ECqqYtOM',
    appId: '1:580866716080:web:f812eac7fd3b46215de675',
    messagingSenderId: '580866716080',
    projectId: 'dinner-app-18bdc',
    authDomain: 'dinner-app-18bdc.firebaseapp.com',
    storageBucket: 'dinner-app-18bdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERiprqTlULWCBsD6ONlstw8dbQayS3lU',
    appId: '1:580866716080:android:82f0bf616127e4435de675',
    messagingSenderId: '580866716080',
    projectId: 'dinner-app-18bdc',
    storageBucket: 'dinner-app-18bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4NYKKDRZ4A4pmMFbKz9hWAlppBY1DKk',
    appId: '1:580866716080:ios:2c04de16335c77905de675',
    messagingSenderId: '580866716080',
    projectId: 'dinner-app-18bdc',
    storageBucket: 'dinner-app-18bdc.appspot.com',
    iosBundleId: 'com.example.dinnerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4NYKKDRZ4A4pmMFbKz9hWAlppBY1DKk',
    appId: '1:580866716080:ios:a7787aadd9105fe95de675',
    messagingSenderId: '580866716080',
    projectId: 'dinner-app-18bdc',
    storageBucket: 'dinner-app-18bdc.appspot.com',
    iosBundleId: 'com.example.dinnerapp.RunnerTests',
  );
}
